### ISSUE TITLE
Warn if oveViewId in ove client is invalid

### ISSUE THREAD

**Issue by jamesscottbrown** [ove/ove#108]
It would be helpful if the OVE Client gave an immediate indication to the user if the specified `oveViewId` is invalid, in the form of a message in the page itself that can be seen without opening the console.

There are various ways to get this URL wrong:
 1. capitalizing `oveViewId` wrong (`http://localhost:8080/view.html?oveViewID=LocalNine-0`)
 2. forgetting the space name (`http://localhost:8080/view.html?oveViewId=0`)
3. spelling the space name wrong (`http://localhost:8080/view.html?oveViewId=LocalNne-0`)
4. omitting the oveViewId entirely (`http://localhost:8080/view.html`)
5. using a `.` rather than `-` to separate the space name and clientId  (`http://localhost:8080/view.html?oveViewId=LocalNine.0`)
6. using a clientId that is larger than the number of clients in the space (which could occur if the user forgets that they are zero-indexed)

I've made mistakes 1 and 2 myself, and it has taken me longer than it should have to realise that I had typed the wrong URL, rather than things being broken. 

It would be most useful if this error message also listed the valid URLs as a range for each space that is defined.

**Comment by senakafdo** [comment]
An end user is not meant to type the OVE URLs by hand. They should instead be using a launcher to load them. We should instead make it possible for a user to load the viewers from the landing page or using some tool.

However, at the same time, we should be reporting an error on the console where appropriate. A view.html without the proper oveViewId is an invalid situation. 

There is no need to report this as a pop-up error message. That sets a wrong expectation in terms of UX and people would use the same to report other error messages for consistency. This would also be additional complexity to get the CSS/sizes etc done properly since the viewers also have an embedded-mode of operation etc.

It is an overkill for the error message to provide a valid URL. That is clearly not required.

Think of it like this: an error message telling the user what the valid URLs are must work for every scenario. If for example there is an error in the error message then that is an even greater bug. So, it would be easier to inform the user what the error is and suggest that they use the appropriate tool/landing page to load the correct URLs.

**Comment by jamesscottbrown** [comment]
I agree that in general OVE errors should be reported in the console, rather than displayed in the browser window, because overlaying error messages would further interfere with OVE's function of displaying particular things.

However, this is a different case to most errors, as it prevents the OVE Client from initially loading. If the OVE View has not loaded, then this should be made immediately clear to  the user. If the message only appears in the console, the user will not realise that an error has occurred until a subsequent command apparently has no effect.

If I get the initial part  of the URL wrong, then this is immediately apparent (I get a chrome `This site can't be reached` message if the **hostname** is wrong, or the text `Cannot get /<whatever>` if the **path** is wrong). I think it should be similarly apparent if the **parameters** are wrong, but this error is currently completely invisible unless the console is open.

An alternative to displaying an error page would be redirect to the OVE core index page, which (after https://github.com/ove/ove/pull/114 is merged) will show the correct link formats.

**Comment by senakafdo** [comment]
OVE supports various modes of rendering for its viewers and they can also be on various kinds of clients as well. The error messages and the redirection does not make sense in these scenarios, and we cannot simply destroy the UX of these scenarios in favour of someone who cannot get the URLs written appropriately. An alternative testcase would be to deploy a standard test application, like you check if a screen/projector is working and properly colour balanced. This will help the user diagnose if OVE is properly deployed or not.

#114 wouldn't make sense as a list, since the user would not know which URL is to be loaded on which screen. Instead, it would be better to make the representation of the clients (the rectangles under the spaces section) clickable. We will also need to add a standard text under the name of each space suggesting that the user clicks on the respective rectangle (in some better words of course) to launch the corresponding client.

**Comment by jamesscottbrown** [comment]
> An alternative testcase would be to deploy a standard test application, like you check if a screen/projector is working and properly colour balanced. This will help the user diagnose if OVE is properly deployed or not.

IIRC, there was a previous suggestion of providing a way to display the `oveViewId` in large text in each window: this would test both that all the browsers are working correctly, and that they are arranged in the same pattern as defined in the `Spaces.json` file.


> #114 wouldn't make sense as a list, since the user would not know which URL is to be loaded on which screen. Instead, it would be better to make the representation of the clients (the rectangles under the spaces section) clickable

I disagree extremely strongly. If I want to launch the browsers correspond to space `LocalNine`, I want to be able to *read* that the URLs to load are: `http://192.168.1.108:8080/view.html?oveViewId=LocalNine-0`  ...  `http://192.168.1.108:8080/view.html?oveViewId=LocalNine-8`, which is exactly what is shown.

If I was to instead put links on the rectangles, I would be hiding this: users would have to click on a rectangle before they were able to read a URL, which is significantly worse.

A second problem is that clicking the rectangles representing OVE Clients may be difficult if they are occluded by rectangles representing sections.

> the user would not know which URL is to be loaded on which screen

They can see this by looking at the diagram immediately above the URLs.

![view-urls](https://user-images.githubusercontent.com/338833/52920276-ae602b00-3302-11e9-93d4-817e3c198c57.png)

**Comment by senakafdo** [comment]
> A second problem is that clicking the rectangles representing OVE Clients may be difficult if they are occluded by rectangles representing sections.

This is not a problem. You could render a separate (transparent/border-less) layer of rectangles above everything that will be the links to the specific viewers.

The problem of having a list of URLs would be as follows: If you were a person who was actually clicking on a URL to load a portion of the space, you would most definitely be a person debugging an application on a specific client. Assume you have a 100 screens, unless your list of URLs are paginated the user would have to scroll up and down to see the layout and then select which URL to click on. That's not a good design.

If you were presenting the URL to a person who would want to read and understand it had a pattern, simply write it out as:

```html
The OVE Clients corresponding to this space have the URLs in the format: 
http://192.168.1.108:8080/view.html?oveViewId=LocalNine-<CLIENT_ID>. 
The CLIENT_ID is an integer in the range of 0 to 8.
```

**Comment by senakafdo** [comment]
This issue would be non-existant as a part of #114 and the resolution to #115. Therefore I am closing it as there is nothing specific to be done here. As a summary, we aim to make it convenient for the enduser to use auto-generated URLs to load the viewers in (#114) and we use the splash/diagnostic screen to understand whether OVE is running properly or not. This reduces a number of UX challenges in terms of displaying errors etc.
