### ISSUE TITLE
OVE Clear Sections clears on all spaces?

### ISSUE THREAD

**Issue by davidbirchwork** [ove/ove#32]
This method appears to delete all sections on all spaces

`curl --header "Content-Type: application/json" --request DELETE http://SERVER:8080/sections`

That may be useful but shouldn't we have a method to Delete States on just one SPACE?

**Comment by oserban** [comment]
I will go one step ahead and say that you **should not be allowed** to delete all sections on all spaces. I think this is a safety flaw.

**Comment by senakafdo** [comment]
There are two methods, one to delete a specific section and the other to delete all sections. The delete all sections do not accept a name of a space right now, but that can be provided as a filter criteria. I will make that improvement. The objective of this API method was in fact specifically to delete "all sections" not a subset. It is not a safety flaw, as someone needs to deliberately invoke this API instead of the other one(s).

**Comment by davidbirchwork** [comment]
Shouldn't all spaces be independent by design?

**Comment by senakafdo** [comment]
Now you can do `curl --header "Content-Type: application/json" --request DELETE http://localhost:8080/sections?space=DODev`
