### ISSUE TITLE
Provide support for changing the order of sections

### ISSUE THREAD

**Issue by davidbirchwork** [ove/ove#7]
Currently we rely on order of creation to specify Z index. 
It would be helpful to be able to define Z index during section creation. 
For example the Audio app which is invisible should have a low Z index regardless of when it was created.

**Comment by senakafdo** [comment]
@davidbirchwork, it is a deliberate design decision to prevent manipulation of the z-index of the frames in OVE. If you want to force a low or desired z-index for one/more apps, you can place them accordingly when you create the state.json configuration.

An invisible app creates really no impact on any other app since the iframes are transparent. If your question was with regards to the audio app covering the apps beneath it because of its background, you can fix the CSS of the audio app, instead. I have checked the CSS of the audio app, and it has a \#222 background, which makes it opaque.

I am closing this issue since there seems to be nothing that needs to be fixed here.

**Comment by oserban** [comment]
@senakafdo if I remember correctly, the accidentally created iframes due to the OVE bug were masking events which were not dispatched correctly to the other iframes. This can be an issue with the audio app if it's not displayed correctly under any other apps. Another solution would be to add an invisible app config so that OVE pushes it to the back.

I think there is a bit of discussion to be done here.

**Comment by senakafdo** [comment]
@oserban - that was a bug and [that was fixed](https://github.com/ove/ove/commit/c9b53b244a79f7f8bf68239840e49e103a58a54b#diff-e732ab068bfa086962a31a06589d10f1). An answer to a bug would be to fix it and not to workaround it, :). So same applies to the audio app (if it was a bug in it) or to OVE core - we must fix the bug, not retain it and provide an alternative way to avoid it.

-1 on random changes like _an invisible app config so that OVE pushes it to the back_. We have a standard for this and that is:
1. The order of the sections are the way you configure it in the state configuration. If you don't like the order, you can re-order it.
2. If your app needs to be invisible **fix the CSS**. That will make it invisible.

A [z-index means](https://developer.mozilla.org/en-US/docs/Web/CSS/z-index) how objects will be stacked on a browser. It has absolutely nothing to do with how OVE messaging works, which is based on the sectionId. Changing the z-index has zero-impact on the sectionId.

I will keep the issue open, but unless there is a compelling reason this behaviour will not be changed, :).

**Comment by davidbirchwork** [comment]
@senakafdo consider the case that sections are created at runtime interactively. Not every visualisation is Static. 
 E.g. a base app and over lay transpartent highlight apps. 
consider the case when the users wants to change the base app while keeping the transparent apps on top. 

Users should be able to specify the Z index when creating sections. 

further if a user wants to temporarily hide an overlay or swap between two overlays they should be able to change the Z index of a section.

**Comment by senakafdo** [comment]
Having an ordering system for sections is an acceptable improvement. Currently we have a flat-list so there is no grouping as such, and therefore there is no concept of section 3 getting in between sections 1 and 2. If this needs to be supported, we can do that. But not by saying section N is on z-index M.

**Comment by senakafdo** [comment]
@jamesscottbrown,

> No, we simply have an _undocumented behaviour in the current software version_, which is that sections are created in the order that requests to create them are received.

We do not have any proper documentation for OVE as yet, so this is not an exceptional situation. Though not related to this issue, we need to ensure all OVE concepts are well documented. And, that will also create a clear distinction between what's a feature and what's a tweak.

**Comment by davidbirchwork** [comment]
@senakafdo provided we support runtime change of grouping / layering then I'll support. 
For example in @jamesscottbrown example what if we wanted to swap the rendering order of Sections 1 and 3 at runtime?

**Comment by senakafdo** [comment]
@davidbirchwork, I'm not sure what's best in that scenario. 

I would expect that a group would always have sections that are stacked back to back (potentially someone's reason for having a group in the first place). 

If however the layout service can support a concept of some sections may lie between other sections within a group, `{1, 3}, {2}`, that's a different story. However, we should also consider the fact that groups may have 100s of sections and the rules may be fairly complex as to what sections support overlapping and all. 

Regardless of how the layout service manages this, the OVE core will map a sectionId to a z-index, so what the layout service can potentially do is to correct all sectionIds as a part of an update request. This is also a good practice from a browser's PoV, because it will not always support movement of frames from one z-index to another without repainting/rendering the content.

**Comment by senakafdo** [comment]
I also think we should also not be doing things in a unique way. Does powerpoint support this kind of behaviour for presentations for instance? If they don't I would expect that they have very good reasons not to.

**Comment by davidbirchwork** [comment]
powerpoint provides very fine grained functionality to change of Z order for display elements and groups  thereof, I think this will be expected by out users and we should replicate 
[see here](https://support.office.com/en-us/article/Change-the-order-in-which-stacked-objects-placeholders-or-shapes-appear-on-a-slide-9A3B64B2-F1AC-42BC-AD97-AB30FAD93DE4) 👍 


options to achieve this:

1) use groups and treat them as an ordered list and have an "InsertAt" API
2) Explicitly provide API to Specify Z index on group/section
3) Provide API to "send2back, send2front,bring forward"..


I think #2 is simplest here

**Comment by senakafdo** [comment]
@davidbirchwork, there seems to be a difference in perception with regards to what PowerPoint supports. Let me list it out to be clear.

Powerpoint supports:
1. Sending layers back, forwards, to back, to front during design-time.

Unless I am mistaken, Powerpoint does not support:
1. Changing order of layers while a show is in progress (i.e. runtime).
2. Allowing end users to specify the order as a number (i.e. z-index) at any point.
3. Allowing content to be inserted between grouped elements.
4. Allow content to be added to (or removed from) a group without ungrouping them first.

Therefore, OVE will support:
1. Allowing users to reorder the layout of sections through the configuration UI or layout service

In my opinion, OVE should not support:
1. Allowing users to specify/manipulate z-index
2. Allowing users to insert content between grouped sections

I fully agree that \#3 from your list above, is something we need to have, but via the configuration UI or layout service. Everything that you can do via the UI will have an API behind it. This is not a feature for OVE core. \#1 and \#2 does not seem to be required.

**Comment by miguems** [comment]
Dear all,
I think you are mixing several things in this discussion.
One thing is the design of the scenario (or whatever name you have given to
a set of sections/apps): for it, the ordering of the json can do this task
as @senakafdo pointed out. Does anyone have problems with this?

Second thing is presenting time. And for this, we can discuss what we can
support or are willing to (so far, I haven't seen any serious discussion on
this). We can go as far as supporting any type of animations (in a
powerpointy way): sections zooming in/out, entering from the sides,
dissapearing... Should this be the case, we need to create an advanced
presenting controller that enables some way of selecting a section and
applying an animated action to it. We can even add timers, delays, and all
the fancy stuff. I do not see this a priority, but it is certainly
eye-catching and tempting.

Best regards!

**Comment by senakafdo** [comment]
@miguems, agree on your thoughts re:presenting time, but my point earlier was that even Powerpoint does not let you reorder the layout of the objects while you are presenting, :) - I may be mistaken, but I cannot find such an option at least on the version I am using.

**Comment by senakafdo** [comment]
Alright, now that we have a different title and scope for this, :), shall we all agree that the feature that we want here is for someone to be able to dynamically re-order sections, but let the framework handle the way sections map to their z-indexes? 

If we agree, we can include this as a part of the layout management for OVE, which is provided by the layout service on behalf of the OVE core. There could very well be changes that has to be introduced into OVE core as a result, but the issue under these circumstances should ideally be a part of layout management.

**Comment by jamesscottbrown** [comment]
I think that the API should provide the following actions:

* `/section/<sectionID>/sendToBack`: Sends the specified section to the back of the stack
* `/section/<sectionID>/sendBackwards`: Sends the specified section towards the back of the stack, behind the next section in the stack that overlaps it; if no other section overlaps it, the stacking order is not changed
* `/section/<sectionID>/sendBackwards/<n>` equivalent to repeating the `sendBackwards` operation `n` times

* `/section/<sectionID>/sendToFront`: Sends the specified section to the front of the stack
* `/section/<sectionID>/sendForwards`: Sends the specified section towards the front of the stack, in front of the next section in the stack that overlaps it; if no other section overlaps it, the stacking order is not changed
* `/section/<sectionID>/sendForwards/<n>`: equivalent to repeating the `sendForwards` operation `n` times

These (apart from the variant that repeats `n` times) are the standard operations provided in most vector graphics (or desktop publishing) software.

**Comment by senakafdo** [comment]
@jamesscottbrown, need to decide on whether this is the right API for it, but thanks for the list.

**Comment by senakafdo** [comment]
It is not possible to move sections in between other sections without having some understanding of their layouts etc. This is only computable by a layout service which can process this kind of requirement. 

Also, OVE also will not be able to move a section ahead of one but not all sections without changing z-indexes of all affected sections. The z-index is one-to-one with the section number to avoid any complexity of computing that. So, what the layout service will have to eventually do is to request OVE to change the section number of any sections for which the ordering has changed.

It also not possible for OVE to swap a section number of an existing section since application cache state based on the section numbers and groups keep track of what sections are a part of it based on section numbers. So, effectively this would redo the complete layout and re-stack all sections.

It must be noted that it is possible to replace an application of an existing section by changing the application associated with the section: OVE provides APIs for this. Therefore, after computing the changes to the layout, the layout service can make use of OVE APIs to reorder sections appropriately. If done right, it should produde a fade in/out effect for affected sections.
