### ISSUE TITLE
Index page

### ISSUE THREAD

**Issue by jamesscottbrown** [ove/ove#75]
Currently, OVE does not have a useful index page: if a user opens a URL like `http://localhost:8080` in their browser, they see a blank page.

This is not useful: if they wanted a blank page they could open `http://localhost:8080/view.html` instead.

It would be more useful if they instead saw a page that:

* Had a title telling them that OVE is running correctly, and that is what is being served on this port
* had a 1 paragraph description of what OVE is
* had a paragraph with similar information to the [Using OVE](https://github.com/ove/ove-docs/blob/master/docs/USAGE.md) page, explaining how to use OVE
* has a link to the documentation site, their local Swagger API docs, the section list page proposed in #69  (if it is created), and the GUI (once it exists)

**Comment by senakafdo** [comment]
Ok, so #69 does make sense if we do something like this. There is really less value in having a separate page for that. We can rather have a collapsible section within the index page of OVE.

In terms of documentation, there is no point in duplicating the contents of Using OVE page in here. We can provide a link to the documentation site, instead.

In terms of the API documentation, we should also provide links to the Swagger API docs of the individual apps as well. This can be a part of the section list, since we know the links to the correspoding apps at that point.

**Comment by senakafdo** [comment]
> I don't think is possible to link to the Swagger docs for which no sections have been created, as OVE doesn't know where they're running (at least until they're all being proxied by the Security Proxy).

This is why I noted this needs to be a part of the section list. When you create a section, regardless of whether you have a Security Proxy or not, you need to provide a Section URL. When we have a proxy and if there needs to be two URLs instead of one (external vs internal), we can figure how to use an internal URL to get the corresponding external URL or vice versa.
