### ISSUE TITLE
Improve error reporting on OVE when actions failed

### ISSUE THREAD

**Issue by jamesscottbrown** [ove/ove#93]
@oserban and I just spent a while failing to display a Chinese New Year banner, before realising that we were not using the correct space name when creating the section.

It would be helpful if OVE returned an error like `"Invalid space name"`, rather than just `{}`. This should be easy to check, as the spaces are defined in `Spaces.json`.

**Comment by oserban** [comment]
I think the overall error reporting in OVE needs to be improved. When something is failing it should be reported back not just ignored.

**Comment by oserban** [comment]
BTW, OVE was sending a 200 while something failed, so it should raise at least a 500 error when something is failing.

**Comment by senakafdo** [comment]
I think the issue here is down to using the wrong operation and expecting it to fail rather than the operation not failing. 

The operation that you attempted, will return errors when you asked it to do something it can understand but with incorrect parameters. 

If you gave it parameters it does not understand it will do nothing and subsequently say it made no change, which is what "{}" with a 200 means. This is not a deliberate design, but this is typically what it is today because of a missing check to see if the request body had something it could not understand.

This is probably not so informative to the caller, since they would be expecting something to happen and nothing does in this case. I will therefore review all such scenarios and ensure we report an 'invalid operation' with a 400 status code. 

However, a 500 status is wrong, since there is no server-side error in this case.
