### ISSUE TITLE
Report errors when creating/updating applications with invalid state information

### ISSUE THREAD

**Issue by oserban** [ove/ove#97]
There should be an error raised when:

1. an invalid OVE space is passed
2. An incomplete or invalid request is passed (e.g. an app config with missing parameters)
3. An invalid state is passed to the ove app (e.g. the state of the maps app is passed accidentally to the images app)
4. In general OVE should relay any error raised by the app when creating a section

**Comment by senakafdo** [comment]
@oserban, we can start by writing some test cases for 1 and 2 if they don't exist, but I would expect a majority of the combinations of 2 and almost all of the combinations of 1 to be already covered, unless you attempted to call and endpoint that did not accept the kind of payload you were passing and therefore reported no relevant error, which was fixed in a couple of APIs around updating sections.

3 and 4 on the other hand may not at all be covered, and we will have to put in place stronger validation around it. Apps also lack good test cases for the APIs they expose, as reported in #48, so we cannot be certain that we have 100% code coverage etc.

**Comment by jamesscottbrown** [comment]
I think you mean https://github.com/ove/ove-apps/issues/48, not #48.

**Comment by senakafdo** [comment]
Point 3 of @oserban's request is now implemented at the ove-core level, and needs to be made use of at an application level. Point 4 however cannot be fixed easily as OVE will never be able to relay errors that come up during a non-blocking call of instatiating an app. The app however will be logging an error if the state was invalid.

**Comment by oserban** [comment]
Point 4 can be implemented async. When you create a section, if the app raises an error OVE will get that error back and can be saved as a section error if you do something like GET /sections/sectionId/status

**Comment by senakafdo** [comment]
That is not a good idea, unless you want to store just one error message. If you store more than one error message it will become a memory bottleneck. So, can we limit this to a single error message?

**Comment by oserban** [comment]
Yes. it's going to be one error message per section, which is the last status of that section.
